### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Binocularbath** [bootchk/resynthesizer#123]
Hello everyone
Im getting this error message. Any idea how i can solve?

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

**Comment by FaceCrap** [comment]
I've got the exact same issue
``` 
Traceback (most recent call last):
  File "E:\PortableApps\GIMPPortable\App\gimp\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "E:\PortableApps\GIMPPortable\App\gimp\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "E:\PortableApps\GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins\plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found
```
I'm 100% positive I've installed the plugin in the correct location i.e.  ```....\lib\gimp\2.0\plug-ins``` as you can see in the traceback. 
GIMP version is 2.10.34 (Revision 2)

After installing, the options I expected to see in Filters > Enhance do show up, but the one I am supposed to see in Filters > Map do NOT show... there is no option "Resynthesize"

**Comment by FaceCrap** [comment]
Ok, Fixed it, the instructions mentioned in the README_WINDOWS.txt file included in the zip are omitting one very important detail. Currently, it states to place ALL files in the plugin folder. 
What it should have mentioned is that both executables need to be in a PATH folder, once I placed them in a folder present in my PATH env.var. it ran without any issue and the Resynthesize option showed up in Filters > Map
