### ISSUE TITLE
Flatpak resyntherizer heal selection not working

### ISSUE THREAD

**Issue by meowgoober** [bootchk/resynthesizer#134]
dorker@debian:~$ neofetch
       _,met$$$$$gg.          dorker@debian 
    ,g$$$$$$$$$$$$$$$P.       ------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: OptiPlex 5040 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-26-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 33 mins 
 $$P      d$'     ,    $$P    Packages: 1925 (dpkg), 17 (flatpak) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: Plasma 5.27.5 
 `$$b      "-.__              WM: kwin 
  `Y$$                        Theme: [Plasma], Breeze [GTK2/3] 
   `Y$$.                      Icons: [Plasma], breeze-dark [GTK2/3] 
     `$$b.                    Terminal: konsole 
       `Y$$b.                 CPU: Intel i5-6500 (4) @ 3.600GHz 
          `"Y$b._             GPU: Intel HD Graphics 530 
              `"""            Memory: 2909MiB / 15877MiB 

                                                      
                                                      
                                                      

![image](https://github.com/user-attachments/assets/8721dba9-e50a-4cd3-94d3-ae828a34a45a)

Traceback (most recent call last):
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "/app/lib/gimp/2.0/python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "/home/dorker/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

![image](https://github.com/user-attachments/assets/40a83673-6058-4fa2-8c19-64676b9ee895)
![image](https://github.com/user-attachments/assets/da4cc4ef-0a4e-4f92-826b-b08d846be44c)

**Comment by meowgoober** [comment]
since the neofetch thing is a little weird here, here it is:

dorker@debian:~$ neofetch
       dorker@debian 

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: OptiPlex 5040 
Kernel: 6.1.0-26-amd64 
  Uptime: 33 mins 
  Packages: 1925 (dpkg), 17 (flatpak) 
 Shell: bash 5.2.15 
  Resolution: 1920x1080 
 DE: Plasma 5.27.5 
   WM: kwin 
   Theme: [Plasma], Breeze [GTK2/3] 
    Icons: [Plasma], breeze-dark [GTK2/3] 
   Terminal: konsole 
  CPU: Intel i5-6500 (4) @ 3.600GHz 
  GPU: Intel HD Graphics 530         
   Memory: 2909MiB / 15877MiB 

                                                      
                                                      


dorker@debian:~$

**Comment by JohnVV** [comment]
try installing the gimp deb 
i have NEVER!!! had good results with flatpack or appimage

**Comment by CHJ85** [comment]
@JohnVV I Have the same problem but with the source code version on Kubuntu 22.04. Where is the GIMP deb?

**Comment by bootchk** [comment]
This is a packaging or building issue.

The error "plug-in-resynthesizer not found" means that the engine plugin is not properly installed.
This is a very common problem, discussed in other issues and in the wiki.

Closing as a duplicate.
