### ISSUE TITLE
Heal selection not working in GIMP 2.8.20 on macOS

### ISSUE THREAD

**Issue by revolter** [bootchk/resynthesizer#41]
When I make a selection and go to `Filters` > `Enhance` > `Heal selection...`, I get these errors:

> Calling error for procedure 'gimp-procedural-db-proc-info':
Procedure 'plug-in-resynthesizer' not found

and

> An error occurred running python_fu_heal_selection
>
> error: procedure not found
>
> Traceback (most recent call last):
  File "/Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/python/gimpfu.py", line 736, in response
    dialog.res = run_script(params)
  File "/Applications/GIMP.app/Contents/Resources/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/Users/iulian/Library/Application Support/GIMP/2.8/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

Could this be related to the fact that `Filters` > `Map` > `Resynthesize...` is missing?

This is the content of the plug-ins folder:

```
 17:00:19 ~/Library/Application Support/GIMP/2.8/plug-ins
> ls -al
total 376
drwxr-xr-x  13 iulian  staff    442 Aug 10 17:00 .
drwxr-xr-x  41 iulian  staff   1394 Aug 10 16:46 ..
-rw-r--r--@  1 iulian  staff   6148 Aug 10 16:43 .DS_Store
-rwxr--r--@  1 iulian  staff   6595 Apr 13  2011 plugin-heal-selection.py
-rwxr--r--@  1 iulian  staff   3153 Apr 13  2011 plugin-heal-transparency.py
-rwxr--r--@  1 iulian  staff  17194 Apr 13  2011 plugin-map-style.py
-rwxr--r--@  1 iulian  staff   7684 Apr 13  2011 plugin-render-texture.py
-rwxr--r--@  1 iulian  staff   3303 Apr 13  2011 plugin-resynth-enlarge.py
-rwxr--r--@  1 iulian  staff   3609 Apr 15  2011 plugin-resynth-fill-pattern.py
-rwxr--r--@  1 iulian  staff   3262 Apr 13  2011 plugin-resynth-sharpen.py
-rwxr--r--@  1 iulian  staff   6011 Apr 13  2011 plugin-uncrop.py
-rwxr-xr-x@  1 iulian  staff  62838 Apr 16  2011 resynthesizer
-rwxr-xr-x@  1 iulian  staff  53607 Apr 16  2011 resynthesizer-gui
```

**Comment by bootchk** [comment]
Off the top of my head, may be wrong, requires further study.... yes, related,  resynthesizer-gui should show the Map>Resynthesizes menu item.   The PDB part of Gimp scans the plugin directory as Gimp starts.   I don't know how the Gimp PDB recognizes plugins, maybe it looks for the .exe suffix (as well as .py) ?   Or aren't the C-language plugins (resynthesizer and resythesizer-gui) installed in a different directory than the Python plugins?  Or is it the "plugins" directory, not "plug-ins".  I presume you are building it yourself.  I have little experience building it for Mac OS X.  Let me study some more...

**Comment by revolter** [comment]
Being on macOS, they don't have an `.exe` extension. The `plug-ins` folder was already there, also, the `.py` plugins are working in that location. No, I downloaded it from [here](http://registry.gimp.org/node/27986).

**Comment by bootchk** [comment]
You're right, I was just blue-skying.  But you downloaded from a site that doesn't have Mac OS X executables?  The executable (C-language, not Python) plugins must be compiled for the platform or the platform won't recognize them as executables.  Try downloading from a site where the executables are specifically built for Mac OS X.  The Python scripts will run on any platform that has Gimp installed, but the Python plugins all invoke the C-language executable plugin resynthesizer.

**Comment by revolter** [comment]
I tried building this myself but stumbled upon the same issue as in #23 :(
