### ISSUE TITLE
Not work in Fedora 31

### ISSUE THREAD

**Issue by eexpress** [bootchk/resynthesizer#70]
error output.
```
Traceback (most recent call last):
  File "/usr/lib64/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/usr/lib64/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/usr/lib64/gimp/2.0/plug-ins/plugin-resynth-sharpen.py", line 79, in plugin_main
    pdb.plug_in_resynthesizer(
gimp.error: procedure not found
```
plugin info. installed from repo.
```
⭕ pinfo gimp-resynthesizer
Name        : gimp-resynthesizer
Version     : 2.0.3
Release     : 2.20190428gitadfa25a.fc31
Architecture: x86_64
Install Date: Sat Jan 25 23:11:20 2020
Group       : Unspecified
Size        : 183934
License     : GPLv2+
Signature   : RSA/SHA256, Sun Sep 29 02:25:23 2019, Key ID 50cb390b3c3359c4
Source RPM  : gimp-resynthesizer-2.0.3-2.20190428gitadfa25a.fc31.src.rpm
Build Date  : Thu Sep 26 23:24:30 2019
Build Host  : buildvm-02.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/bootchk/resynthesizer
Bug URL     : https://bugz.fedoraproject.org/gimp-resynthesizer
Summary     : Gimp plug-in for texture synthesis
```
gimp version
```
GNU Image Manipulation Program version 2.10.14
```

**Comment by bootchk** [comment]
I think you invoked "Filter>Sharpen by resynthesis" which seems to have found the file /usr/lib64/gimp/2.0/plug-ins/plugin-resynth-sharpen.py but that file invokes (calls as a subroutine) the plugin found in /usr/lib64/gimp/2.0/plug-ins/plugin-resynthesizer.  That latter file should be an executable file (it was compiled from C) and should have executable permissions.  Can you please check that file exists and has the current permission?  If not, then the package (created by RedHat/Fedora) may be flawed.  I think I can build a Fedora testing harness, but I don't regularly do so, and it might take me awhile.

**Comment by ranjithsiji** [comment]
It is working perfectly in Fedora 32. My gimp version is 2.10.20
