### ISSUE TITLE
Procedure 'plug-in-resynthesizer' returned no return values

### ISSUE THREAD

**Issue by AneudyM** [bootchk/resynthesizer#86]
Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "C:\Users\amota\AppData\Roaming\GIMP\2.10\plug-ins\plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
RuntimeError: Procedure 'plug-in-resynthesizer' returned no return values

**Comment by bootchk** [comment]
This means the resynthesizer crashed.  It runs as a separate process.  The error message is from the GIMP app which continues to run.  The message offers no clues about the circumstances of the crash.

This is the first report of a crash in years.  The first step is to reproduce it.  If you know the image and sequence of steps that can reproduce the crash, and also what version of GIMP, what platform/OS, and where you obtained the resynthesizer, please post them here.

**Comment by tanius** [comment]
I have a crash with the same symptoms, and can reproduce it (or at least, it happened several times with the same steps yesterday). Using GIMP 2.10.18 under Ubuntu 20.04, with Resynthesizer installed from Ubuntu package `gimp-plugin-registry`.

Turns out it happens only when calling "Filter → Map → Resynthesize…" on a small selection of a very large (10,000×8,000 px) picture, in my case a JPG. When taking over a small relevant part of that image into a new image (800×400 px in my case) and then working on just that, Resynthesizer works just fine. 

Maybe it helps somebody with the same issue.

**Comment by bootchk** [comment]
Thanks.

Its is probably a known issue: large images can cause a crash.  Resynthesizer reads the entire image into its own memory.  I am not sure there is a good fix.  It is rare, but it seems to be reported more often as users use larger and larger images.

**Comment by acheong08** [comment]
The error occurs only in flatpak. It works on the deb version but the python plugins don't

**Comment by bootchk** [comment]
Well this issue reported a symptom that is a error message that is doesn't give enough information to diagnose.

Given the additional information that it happens on huge images, you can say that the issue is caused by running out of memory, and I can't fix it.

If you get the error on a small image, then maybe it is a new issue.  Please upload the image and tell me exact details, such as what OS, what version of GIMP, what version of resynthesizer, and what GUI steps you took (Heal selection  or Map>Resynthesize ?). Does it always fail, or only sometimes?

**Comment by acheong08** [comment]
> Does it always fail, or only sometimes?
It always fails

OS: Ubuntu 22.04
GIMP: 2.10 on flatpak (latest org.gimp.GIMP)
resynthesizer: I tried with the latest org.gimp.GIMP.Plugin.Resynthesizer from flatpak and also tried to compile and copy it manually. The same error occured

Workaround: I used an AppImage from aferrero2707/gimp-appimage. It's of a much older version of Gimp (I'm not sure exactly.)

The error is the exact same as the one listed above in this issue.

**Comment by rortega67** [comment]
I got the same issue on Windows on GIMP 2.10.34
